### ISSUE TITLE
client.GetTransactionStatusRequest should probably contain virtual chain id

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-spec#105]
```
message GetTransactionStatusRequest {
    primitives.timestamp_nano transaction_timestamp = 1;
    primitives.sha256 txhash = 2;
}
```

there's no way to verify you're accessing the correct virtual chain

**Comment by OdedWx** [comment]
Done, added also protocol_version.
Commit message "Added protocol_verison, virtualchain id to GetTarnsactionStatus client request (aligned with the behaviour description)"
