### ISSUE TITLE
Consensus Context - Block Creation spec

### ISSUE THREAD

**Issue by IdoZilberberg** [orbs-network/orbs-spec#111]
https://github.com/orbs-network/orbs-spec/blob/master/behaviors/services/consensus-context.md

1) Weighted random sorting algorithm, and taking reputation into account in `RequestOrderingCommittee` is not explained.
2) `RequestValidationCommittee` spec is identical to `RequestOrderingCommittee`
3) Define someplace a hard minimum for the number of committee members - Lean Helix won't work anyway with less than 4.

**Comment by OdedWx** [comment]
1. Weighted random sorting sorts the nodes (public keys) using their reputation as a weight. An example for a sorting algorithm:
For each node calculate a weighted grade: 
   weighted_grade = 32LSB of SHA256(seed, node_public_key) * Reputation
Sort the nodes based on their weighted_grade, choosing the nodes with the max grade. (The node with the maximum weighted_grade is the leader).

2. Initially both are identical and only `RequestValidationCommittee` is implemented.

3. Right, should be part of the consensus algo.

**Comment by IdoZilberberg** [comment]
@OdedWx 

1. In https://github.com/orbs-network/orbs-spec/blob/master/behaviors/services/consensus-context.md, 
in both RequestNewTransactionsBlock and RequestNewResultsBlock, 
The new tx and rx blocks need to receive "MerkleRoot". I consulted Noam and Ron, so the question that remains now is:
How do you create a MerkleDiff (key/value) from a transaction and from a result?

One suggestion by Noam and Rom was to have key=sequential # of tx in block, and value=txhash.

2. What is the difference between "transaction result" and "transaction receipt"?

**Comment by OdedWx** [comment]
#1 transactions merkle: right, key = tx_index, value = txhash
     receipts merkle: key = tx_index, value = SHA256(serialized receipt)

#2  In some error cases there's no receipt (for example on pre-order checks causing the transaction not to be added to the block or time expired)

**Comment by IdoZilberberg** [comment]
The calculation of items marked with question mark is not specified, need to be shortly explained in spec (file: interfaces/protocol/blocks.proto)

```
message ResultsBlockHeader {
    primitives.protocol_version protocol_version = 1;
    primitives.virtual_chain_id virtual_chain_id = 2;
    primitives.block_height block_height = 3;
    primitives.sha256 prev_block_hash_ptr = 4; // primitives.sha256(ResultsBlockHeader)
    primitives.timestamp_nano timestamp = 5;
    primitives.merkle_sha256 receipts_root_hash = 6;
    primitives.sha256 state_diff_hash = 7; // ?
    primitives.sha256 transactions_block_hash_ptr = 8;
    primitives.merkle_sha256 pre_execution_state_root_hash = 9;
    primitives.bloom_filter txhash_bloom_filter = 10; // ?
    primitives.bloom_filter timestamp_bloom_filter = 11; // ?
    uint32 num_transaction_receipts = 12;
    uint32 num_contract_state_diffs = 13;
}

```

**Comment by IdoZilberberg** [comment]
bloom_filter - nil
Not impl at the moment.

**Comment by IdoZilberberg** [comment]
@OdedWx I missed something here - `primitives.sha256 state_diff_hash = 7;`
How do you calculate a has of state diffs? This is the method I'd want to implement.

```
func calculateStateDiffHash(diffs []*protocol.ContractStateDiff) (primitives.Sha256, error) {
	// ???
}
```

**Comment by IdoZilberberg** [comment]
@OdedWx Also how to calculate receipts merkle hash root, and state diff (see https://github.com/orbs-network/orbs-spec/blob/master/behaviors/services/consensus-context.md#validate-transaction-execution)

**Comment by OdedWx** [comment]
Committee ordering moved to _Committee contract along with the reputation.
#2,#3 were closed before then.
