### ISSUE TITLE
Intra node block sync - contract deployment

### ISSUE THREAD

**Issue by ronnno** [orbs-network/orbs-spec#114]
If BlockStorage contains contract deployment resources in addition to simple state diff we need to specify the process of deploying contracts during intra node sync.

If it does not, how does contract deployment propagate during intra node sync?  

need to update:
https://github.com/orbs-network/orbs-spec/blob/master/behaviors/flows/intra-node-sync.md

**Comment by OdedWx** [comment]
Agree, the Statediff doesn't have all indications (for example the transaction to execute).
We need to separate the issue to 2 parts: 
1. compilation - each node needs to compile
2. Running the constructor - problematic to run as it may depend on the state previous transaction in the block. It may also update the state 

Options: 
1. Compile then apply the block's state diff. (don't run the constructor). #1 is the simplest however, it doesn't enable a way to compare the complication hash. (May be ok as long as eventually we get consensus on the outputs on sequential blocks)
2. StateDiff per transaction - apply "regular" transactions and execute the deploy ones (implies that the state update compile constructor are now in order).
3. Reconsider to do execution on node sync without PreOrder

**Comment by talkol** [comment]
discussed face to face

**Comment by ronnno** [comment]
Do you think this justifies a "Flow" page for contract deployment? This is important design points and it's not in the spec.
