### ISSUE TITLE
Terminology - some remarks

### ISSUE THREAD

**Issue by avilanthe1** [orbs-network/orbs-spec#18]
When explaining what a **node** is: _"The number of nodes in the network is the number of known public keys in the network"_.

The number of known public keys should only increase but the number of nodes may change. Example: consider the case a node changes his public key due to a security breach of its secret key being compromised. Nodes that want to synchronize with the blockchain will have to recognize this node’s public key before and after the change. So if they see a signature (with respect to this node old public key) on an old block they’ll know it is valid.

I further want to highlight a security decision that is (implicitly) made after the definitions of **node** and **virtual chain**. 
A node is said to be _"represented by a public key"_.
And : _“A single node participates in the consensus process of multiple virtual chains (ideally all of them)”_.
It is that the same public key (and hence secret key) representing the same node over all virtual chains, therefore a compromised secret key on one chain jeopardizes all of the virtual chains.

**Comment by talkol** [comment]
I will improve terminology, thanks
