### ISSUE TITLE
Services configuration with smart contracts - possible?

### ISSUE THREAD

**Issue by avilanthe1** [orbs-network/orbs-spec#22]
On one hand [smart contract](https://github.com/orbs-network/orbs-spec/blob/master/terminology.md) is said to be: 

> Code that is deployed by an app developer and executes on the virtual machine of the node. The main purpose of the network is to execute these smart contracts **under consensus**.

On the other hand [services configuration](https://github.com/orbs-network/orbs-spec/blob/master/behaviors/config/services.md)  is said to be:

> Configuration is an in-memory object given to every service on initialization. The object can be created based on static configuration files but will **ultimately be controlled by the management virtual chain via smart contracts**.

Implementing services configurations in smart contracts so it will be under consensus can usually be achieved only partially and sometimes it can't be achieved at all. 
For example, limits such as maximal block size can only be partially verified since any node determining a lower maximal block size will reach a consensus on its proposed blocks. 
Furthermore reaching a consensus on timeouts and so on is impossible.

To conclude, the configuration itself can easily reach consensus in the network but executing it not.

**Comment by avilanthe1** [comment]
### More about: **why configuration can't be part of a smart contract?**

Before I start, I'll just emphasize what the proposal is all about. It's about using the right semantics but nonetheless it is also about emphasizing an important concept in the blockchain/distributed area. 


Starting from the end, what is a **smart contract**?

**Contract**:
> a written or spoken agreement, especially one concerning employment, sales, or tenancy, that is intended to be enforceable by law.

Contract reflects agreement and as you know there must be more than one entity to have an agreement.

**Smart**:
Some times it reflects it Turing-completeness but nonetheless it is a code.


So smart contract has to be an _agreed upon code_ .
Making a code with operations that can be interpreted differently by different computers/compilers/etc. can't be smart contract and the same goes (as explained in the first post) to configurations. 
Imagine you have to explain someone what is a smart contract in Orbs. It can be something like the explanation above or it can be: "smart contract is a code that 99% of it is agreed upon by all and when some entity runs it, it would be like any other entity runs it - EXCEPT for this small configuration thing,  that you can't really know that everyone runs the same thing".

Obviously it is very desired to keep all what is 100% can be agreed upon and run in the same matter in one semantic field of smart contract and the rest as "local code" or "local configurations" or something similar. Making a clear distinction between what is agreed upon and what is not is important since it will help mitigate bugs, ambiguous code, and security vulnerabilities in smart contracts.

**Comment by talkol** [comment]
I'll improve the definition of a smart contract under terminology

I'll also change the word "object" to "data" in the configuration by smart contract section

**Comment by talkol** [comment]
The idea of configurations that are controlled by smart contracts is this: Suppose we have a configuration parameter like `transaction_expiration_timeout = 30 minutes`. We want to allow this value to be changed. Since it's part of the protocol core, it must be changed under consensus of node operators / federation members / etc. The code that controls this change, manages the vote and expresses exactly who can vote and how the voting process works - is implemented as a smart contract on the system. The same goes towards the list of available federation members, every time this list changes, it has to happen as a transaction to a smart contract that manages the change under its agreed upon rules.
