### ISSUE TITLE
Two (or more) gateway nodes for the same transaction

### ISSUE THREAD

**Issue by YaDavid** [orbs-network/orbs-spec#25]
In a scenario where a client sends the same transaction to two (or more) different nodes at the same time, some nodes may see one gateway node while other nodes see a different gateway node. In that case it's unclear who is **the** gateway node for that transaction and who should be billed.

**Comment by OdedWx** [comment]
A node associates a forwarded transaction with the GW node that sent it. If a duplicated transaction is received (for example from another node) it is discarded. The ability of different nodes to associate a transaction with different GW nodes should be taken into consideration in the reputation calculation.

**Comment by talkol** [comment]
Under the pending transaction pool in the TransactionPool service, we should specify that the data structure needs to be unique regarding TxId so if the same transaction is sent from different gateways, it will only be stored once

**Comment by OdedWx** [comment]
Done

**Comment by erankirsh** [comment]
@OdedWx maybe worth noting to ourselves somewhere that this is not a bizantyne behavior of the gateway. (For future reputation)
