### ISSUE TITLE
Small issue: transaction pool and pending transaction pool

### ISSUE THREAD

**Issue by YaDavid** [orbs-network/orbs-spec#26]
What is the difference between:
"Adds the transaction as pending to TransactionPool."
"Adds transaction to pending transaction pool."

These two lines appear in the send transaction flow, 5 rows apart.

Looking at the transaction pool service, I could see "Pending transaction pool" and "Committed transaction pool".

**Comment by OdedWx** [comment]
Fixed:   * Send the transaction to `TransactionPool`.
