### ISSUE TITLE
Client Response

### ISSUE THREAD

**Issue by gadcl** [orbs-network/orbs-spec#28]
It is unclear whether the flow is fault\Byz tolerant. 
It seems the gateway node is in charge of replying to the client. In such a case, if the gateway node is to crash\fail the client will not receive a response (while the transaction might have been processed).

**Comment by OdedWx** [comment]
This is correct. A GW node provides a stateful response to a client that sends it a message.
In case the node fails before a response was received, the HTTP session will be closed and the client will have to query the transaction status through another node or alternatively send the same transaction with the same timestamp, knowing that only one instance will be committed.

**Comment by OdedWx** [comment]
Notes:
1. Duplicate pending transaction - rejected with a REJECTED_DUPLCIATE_PENDING_TRANSACTION notification.
2. Duplicate committed transaction returns the first transaction receipt

**Comment by OdedWx** [comment]
Fixed
