### ISSUE TITLE
Q: when does send transaction ends?

### ISSUE THREAD

**Issue by erankirsh** [orbs-network/orbs-spec#9]
in [Transaction Flow](https://github.com/orbs-network/orbs-spec/blob/master/behaviors/flows/send-transaction.md#send-transaction-flow) it is said that:
> this flow ends when the transaction has been added to the pending pool and propagated to all nodes

It seems that it doesn't wait for consensus, which doesn't make sense to me.

**Comment by talkol** [comment]
Fixed in 436ce08b335734749bdd2587b9e940156c230e36
